name: Frontend Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

<<<<<<< HEAD
    - name: Deploy to GitHub Pages
      run: |
        echo "Deploying to GitHub Pages..."
        gh-pages -d dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: Frontend Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

=======
>>>>>>> ef89d8f8b3017180cd57b613522e5138b345fcc7
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
<<<<<<< HEAD
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-app:latest
=======
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-app:latest
>>>>>>> ef89d8f8b3017180cd57b613522e5138b345fcc7
